Update README.md
Needed to get rid of the comma, otherwise I got an error. 

```bin/cli run --config config.json --tool eslint-default CVE-2018-16492 CVE-2020-4066    24s

Could not parse config.json as a JSON file ('{
  "tools": {
    "eslint-default": {
      "bin": "node",
      "args": [
        "/home/user-name/ossf-cve-benchmark/build/ts/contrib/tools/eslint/src/eslint.js",
      ],
      "options": {
        "eslintDir": "/home/user-name/analysis-tools/eslint-2020-12-08"
      }
    }
  }
}')
/Users/.../ossf-cve-benchmark/build/ts/src/util.js:148
        throw e;
        ^

SyntaxError: Unexpected token ] in JSON at position 172

```